# Generated by Django 5.1.3 on 2024-12-01 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción/Detalles')),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('in_progress', 'En Curso'), ('completed', 'Terminado')], default='registered', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(blank=True, related_name='services', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
