# Generated by Django 5.1.3 on 2024-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_technicalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='technicalservice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='technical_services', to='inventory.product'),
        ),
    ]
