# Generated by Django 5.1.3 on 2024-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_technicalservice_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='client_phone',
            field=models.CharField(default='Telefono Desconocido', max_length=20, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='status',
            field=models.CharField(choices=[('registered', 'Registrado'), ('in_progress', 'En Curso'), ('completed', 'Terminado')], default='registered', max_length=20),
        ),
    ]
