# Generated by Django 5.1.3 on 2024-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_category_product_created_at_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='changed_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
